apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ponad
  labels:
    app.kubernetes.io/component: ponad
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: ponad
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ponad
    spec:
      hostNetwork: true
      hostPID: true    # to see netns file under /proc
      priorityClassName: system-node-critical
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      serviceAccountName: ponad
      terminationGracePeriodSeconds: 1
      containers:
      - name: ponad
        image: ponad:dev
        env:
        - name: COIL_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
        ports:
        - name: metrics
          containerPort: 9384
          protocol: TCP
        - name: health
          containerPort: 9385
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
            host: localhost
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
            host: localhost
        volumeMounts:
        - mountPath: /run
          name: run
          mountPropagation: HostToContainer  # to see bind mount netns file under /run/netns
        - mountPath: /lib/modules
          name: modules
          readOnly: true
      initContainers:
      - name: pona-installer
        image: ponad:dev
        command:
        - "/pona-installer"
        env:
        - name: CNI_NETCONF
          valueFrom:
            configMapKeyRef:
              name: pona-config
              key: cni_netconf
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          name: cni-bin-dir
        - mountPath: /host/etc/cni/net.d
          name: cni-net-dir
      volumes:
      - name: run
        hostPath:
          path: /run
      - name: modules
        hostPath:
          path: /lib/modules
      - name: cni-bin-dir
        hostPath:
          path: /opt/cni/bin
      - name: cni-net-dir
        hostPath:
          path: /etc/cni/net.d
