apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: pona
    app.kubernetes.io/managed-by: kustomize
  name: egress-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: egress-controller-role
subjects:
- kind: ServiceAccount
  name: egress-controller
  namespace: system
