apiVersion: apps/v1
kind: Deployment
metadata:
  name: nat-client
  annotations:
    egress.pona.cybozu.com/egress: egress
  labels:
    app.kubernetes.io/component: nat-client
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: nat-client
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: nat-client
      annotations:
        egress.pona.cybozu.com/egress: egress
    spec:
      containers:
      - name: nat-client
        image: ghcr.io/cybozu/ubuntu-debug:22.04
        command: ["sleep"]
        args:
          - infinity
