name: CI
on:
  pull_request:
  push:
    branches:
    - 'main'

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.22 ]
        platform: [ ubuntu-22.04 ]
    name: Small tests
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: make test
